name: Generate Snake GitHub Contribution Graph

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Graph
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Generate Snake GitHub Contribution Graph
        run: npx github-contribution-grid-snake

      - name: Commit and push changes
        run: |
          git config --global user.name "0marKhan"
          git config --global user.email "omakhan98@gmail.com"
          git add .
          git commit -m "Update Snake GitHub Contribution Graph"
          git push
